apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-11T08:28:01Z"
  labels:
    app: siteweb
  name: siteweb
  namespace: default
  resourceVersion: "272474"
  uid: 8a230d15-a838-4e62-9e1c-8943fa9894e7
spec:
  clusterIP: 10.101.200.113
  clusterIPs:
  - 10.101.200.113
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31888
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: siteweb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
