apiVersion: v1
kind: PersistentVolume
metadata:
  name: monnfspv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.202.174
    path: "/srv/nfsshare/"