apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: subsonic
  name: subsonic
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: subsonic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: subsonic
    spec:
      containers:
      - image: yuminstall001/soundbuzz:latest
        imagePullPolicy: Always
        name: soundbuzz
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: subsonic
  name: subsonic
  namespace: default
spec:
  clusterIP: 10.99.191.166
  clusterIPs:
  - 10.99.191.166
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31167
    port: 4040
    protocol: TCP
    targetPort: 4040
  selector:
    app: subsonic
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}